# Data Preprocessing Tools

## Importing the libraries

In [3]:
#importing Library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [4]:
#Importing the dataset
dataset = pd.read_csv('Data.csv')
#assigning independet variable
x = dataset.iloc[:,:-1].values
#assigning dependetend variable
y = dataset.iloc[: , -1].values

In [5]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [6]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [7]:
#import SimpleImputer for insert a mean of all data to missing data 
from sklearn.impute import SimpleImputer
#calculate mean for missing data column
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
#assigning missing data
imputer.fit(x[ : , 1:3])
x[ : , 1:3] = imputer.transform(x[ : , 1:3])

In [8]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


#decleare variable for encoding independent string into number
ct = ColumnTransformer(transformers=[('encode', OneHotEncoder(), [0])] ,remainder='passthrough')
#ecoding the "0"th ndex using OneHotEncoder methode ..remaining is 'no change'-passthrough

#fit the value into data
x = np.array(ct.fit_transform(x))



In [22]:
print(x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [11]:
#encoding string "yes""no" as 0 and 1
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [12]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [13]:
#importing train_test_split for spliting the data set into Trainging set and Test set
#Train set is used to train the model
#test set is used to test the model
from sklearn.model_selection import train_test_split

#x_train -- tain data set for X
#X_test - tets data set for X
#Y_train - tain data set for Y
#Y_test - tets data set for Y

X_train , X_test, Y_train , Y_test = train_test_split(x , y, test_size = 0.2 , random_state=1)



In [14]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [15]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [16]:
print(Y_train)

[0 1 0 0 1 1 0 1]


In [17]:
print(Y_test)

[0 1]


## Feature Scaling

In [18]:
#import StandardScaler for creatinf ferature scaling to avoid data misbehaviour
from sklearn.preprocessing import StandardScaler

#StandardScaler variable changed to sc
sc = StandardScaler()

#fit_transform => it is used to create sclaler value  and by using that sclaler value, tranform  our dataset value as per StandardScaler function value
X_train[ : ,3 : ] = sc.fit_transform(X_train[ : ,3 : ])

#transform => it is used existing sclaler value  and by using that sclaler value, tranform  our dataset value as per StandardScaler function value
#becase we have to use same scaler value for both train and test .if differ scaller value then our result will not be that much accurate
X_test[ : , 3: ] = sc.transform(X_test[ : ,3 : ])

In [19]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [20]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
